SOFTWARE LABORATORY III ASSIGNMENT 13(MINIPROJECT)

Develop a Movie Recommendation Model 
Using the Scikit-learn Library in Python

Import Libraries

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Load dataset

In [4]:
df = pd.read_csv("movie.csv")

df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

Data preprocessing

In [7]:
# Clean any missing data in the 'genres' column (movie descriptions) 
df['genres'] = df['genres'].fillna('') 
 
# Extract relevant columns (Movie Title and Description) 
movies = df[['title', 'genres']] 
 
# Show the first few rows to ensure the data is loaded correctly 
movies.head()

,title,genres
0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,Jumanji (1995),Adventure|Children|Fantasy
2,Grumpier Old Men (1995),Comedy|Romance
3,Waiting to Exhale (1995),Comedy|Drama|Romance
4,Father of the Bride Part II (1995),Comedy

 TF-IDF Vectorization

In [8]:
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['genres'])

print(tfidf_matrix.shape)

(1016, 21)

 Cosine Similarity Calculation

In [10]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [11]:
indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

def get_recommendations(title, cosine_sim=cosine_sim):
    
    idx = indices[title]
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:11]
    
    movie_indices = [i[0] for i in sim_scores]
    
    return movies['title'].iloc[movie_indices]

In [13]:
get_recommendations("Balto (1995)")

241                        Gumby: The Movie (1995)
309                      Swan Princess, The (1994)
608                         Aristocats, The (1970)
387     Secret Adventures of Tom Thumb, The (1993)
1007                          Pete's Dragon (1977)
1010                 Fox and the Hound, The (1981)
0                                 Toy Story (1995)
729         Wallace & Gromit: A Close Shave (1995)
580                                 Aladdin (1992)
694                        Oliver & Company (1988)
Name: title, dtype: object